name: Build macOS App

on:
  push:
    branches:
      - main  # Запускать сборку при пуше в ветку main

jobs:
  build:
    runs-on: macos-latest  # Используем macOS-окружение

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Загружает код из репозитория

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11  # Версия Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install moviepy==1.0.3
        pip install imageio_ffmpeg
        pip install telethon
        pip install flask
        pip install python-dotenv
        pip install pillow
        pip install send2trash
        pip install pyperclip
        pip install cryptg
        pip install pysocks

    - name: Build executable
      run: |
        pyinstaller --onefile --noconfirm --hidden-import=moviepy.editor --hidden-import=imageio_ffmpeg --console "crop.py"  # Обновите путь к скрипту, если необходимо

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: macOS-app
        path: dist/  # Загружает собранные файлы в артефакты
